export enum OrderStatus {
    ORDER_CHECKING = "ORDER_CHECKING", //주문 확인
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED", //지불 완료
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    RETURNED = "RETURNED",
    REFUNDED = "REFUNDED"
}