export enum OrderStatus {
    ORDER_CHECKING = "ORDER_CHECKING",
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    RETURNED = "RETURNED",
    REFUNDED = "REFUNDED"
}