version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb-container
    restart: always
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mariadb
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env

  back:
    image: ${BACK_IMAGE}
    container_name: backend-container
    restart: always
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-container:3306/${DB_NAME}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/credentials.json
      PAYMENT_TOSS_CLIENT_KEY: ${PAYMENT_TOSS_CLIENT_KEY}
      PAYMENT_TOSS_SECRET_KEY: ${PAYMENT_TOSS_SECRET_KEY}
    volumes:
      - ./back/src/main/resources/credentials/credentials.json:/usr/src/app/credentials.json
    env_file:
      - .env

  client:
    image: ${FRONT_IMAGE}
    container_name: client-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - back
    env_file:
      - ./client/.env.docker

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
