version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb-container
    restart: always
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./script/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    env_file:
      - .env

  back:
    image: ${BACK_IMAGE}
    container_name: backend-container
    restart: always
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./back/src/main/resources/credentials/credentials.json:/usr/src/app/credentials.json
    env_file:
      - ./back/.env.prod

  client:
    image: ${FRONT_IMAGE}
    container_name: client-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - back
    env_file:
      - ./client/.env.docker

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
