// app/(admin)/admin/users/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {UserDashboardPage} from '@/pages/admin/users';

export default function Page() {
  return <UserDashboardPage />;
}
