// app/(home)/order/confirmation/[paymentKey]/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {ConfirmationPage} from '@/pages/home/order/confirmation';

export default function Page() {
  return <ConfirmationPage />;
}
