// app/(admin)/admin/payment/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {AdminPaymentPage} from '@/pages/admin/payment';

export default function Page() {
  return <AdminPaymentPage />;
}
