// app/(admin)/admin/dashboard/traffic/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {DashBoardTrafficPage} from '@/pages/admin/dashboard/traffic';

export default function Page() {
  return <DashBoardTrafficPage  />;
}
