// app/(home)/@modal/(.)add-review/[id]/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {AddReviewPage} from '@/pages/home/modal/add-review';

export default function Page() {
  return <AddReviewPage />;
}
