// app/(admin)/admin/category/edit-category/[id]/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {EditCategoryPage} from '@/pages/admin/category/edit-category';

export default function Page() {
  return <EditCategoryPage />;
}
