// app/(admin)/admin/products/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {ProductsPage} from '@/pages/admin/products';

export default function Page() {
  return <ProductsPage  />;
}
