// app/(admin)/admin/dashboard/sales/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {DashBoardSalesPage} from '@/pages/admin/dashboard/sales';

export default function Page() {
  return <DashBoardSalesPage />;
}
