// app/(admin)/admin/category/add-category/[id]/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import AddCategoryPage from '@/pages/admin/category/add-category';

export default function Page() {
  return <AddCategoryPage  />;
}
