// app/(admin)/admin/dashboard/real-time/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {DashBoardRealTimePage} from '@/pages/admin/dashboard/real-time';

export default function Page() {
  return <DashBoardRealTimePage />;
}
