// app/(admin)/admin/products/add-product/page.tsx

/** AUTO-GENERATED BY fix-app-pages.mjs */
import {AddProductPage} from '@/pages/admin/products/add-product';

export default function Page() {
  return <AddProductPage/>;
}
