/** AUTO-GENERATED BY fix-app-pages.mjs */
import {EditCategoryPage} from '@/pages/admin/category/edit-category';

export default function Page(props: any) {
  return <EditCategoryPage {...props} />;
}
